footer completed
BuildForSDGCohort2/Team-225-Frontend pull request #14
Opened 2020-08-25 19:10 UTC by okorie2

footer created for the webapp

2020-08-25 19:47 UTC, highman95 approved these changes

2020-08-25 20:28 UTC, SaidiAli reviewed
Resolve conflict please. Will merge after.

2020-08-26 05:43 UTC, Austinove commented on src/App.js
>  import React,{Component} from 'react';
Please @okorie2 I think you try to use either a function of the class but not with both named with the same name.
Try to combine them and check if the whole application is running successfully.

2020-08-26 05:46 UTC, Austinove commented on src/App.js
>    }
@okorie2  I think you should add the footer in the `index.js` in the `components ` folder where `AppHeader `is also linked

2020-08-26 05:49 UTC, Austinove requested changes
Please look at the comments i have put in your changes. this will make the whole flow of the project. dont forget to pull updates from `staging-1` before pushing

2020-08-26 05:55 UTC, closed without merging

2020-08-26 05:57 UTC, okorie2 commented
In a bid to properly resolve conflicts, I'm closing this pr. A new one will be made