Ft booking form
BuildForSDGCohort2/Team-225-Frontend pull request #37
Opened 2020-09-09 15:24 UTC by ampaire

I implemented the booking form for the hotels

2020-09-09 19:08 UTC, Austinove commented on src/components/views/BookingForm/Form.js
> +export default BookingForm;
It seems like you did not include the forms in the project views.
And i like the way you comment your work.

2020-09-09 19:09 UTC, Austinove requested changes
well done, but i could't see the forms

2020-09-10 17:20 UTC, SaidiAli requested changes
The PR had conflicts

2020-09-25 13:31 UTC, SaidiAli commented
Sorry, but I had to close this.

2020-09-25 13:31 UTC, closed without merging