Footer
BuildForSDGCohort2/Team-225-Frontend pull request #41
Opened 2020-09-12 00:48 UTC by okorie2

I have worked on the facilities page, although not to a point of perfection.
later today, I will make the page have a more responsive effect.

2020-09-12 06:39 UTC, Austinove requested changes
Hello Please try to resolve the conflicts between your branch and develop. 
Try to do this while resolving the conflicts.
Try to remove the `debug.log` and `components/NavBar/index.js`. so that it matches with develop.

2020-09-12 11:05 UTC, highman95 submitted a review, later dismissed

2020-09-12 18:12 UTC, SaidiAli requested changes
Resolve conflicts

2020-09-13 00:36 UTC, closed without merging

2020-09-13 00:36 UTC, okorie2 commented
in a bid to resolve conflicts, I have to close this pull request